name: Run Model Tests and Inference

on:
  push:
    paths:
      - '**.py'
      - 'config.yaml'

jobs:
  test-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set environment variables
      run: |
        echo "HUGGINGFACE_TOKEN=${{ secrets.HUGGINGFACE_TOKEN }}" >> $GITHUB_ENV
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
        echo "SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL }}" >> $GITHUB_ENV

    - name: Run tests
      run: python tests/test_model.py

    - name: Run experiment
      run: python main.py

    - name: Notify Slack (optional)
      if: always()
      run: |
        python -c "from notify import notify_slack; notify_slack('✅ GitHub Actions: 実験とテスト完了')"
